/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 72
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 38
#define ALIAS_COUNT 0
#define TOKEN_COUNT 21
#define EXTERNAL_TOKEN_COUNT 4
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_config = 1,
  anon_sym_js = 2,
  anon_sym_LBRACE = 3,
  anon_sym_RBRACE = 4,
  anon_sym_pre_operations = 5,
  anon_sym_post_operations = 6,
  anon_sym_input = 7,
  anon_sym_DOLLAR_LBRACE = 8,
  anon_sym_COMMA = 9,
  anon_sym_LBRACK = 10,
  anon_sym_RBRACK = 11,
  anon_sym_COLON = 12,
  sym_property_identifier = 13,
  aux_sym_string_token1 = 14,
  aux_sym_string_token2 = 15,
  sym_comment = 16,
  sym_sql_text = 17,
  sym_block_sql_text = 18,
  sym_js_body = 19,
  sym_js_expression = 20,
  sym_source_file = 21,
  sym_config_block = 22,
  sym_js_block = 23,
  sym_pre_operations_block = 24,
  sym_post_operations_block = 25,
  sym_input_block = 26,
  sym__sql_block_body = 27,
  sym_interpolation = 28,
  sym_object = 29,
  sym_array = 30,
  sym_pair = 31,
  sym__value = 32,
  sym_string = 33,
  aux_sym_source_file_repeat1 = 34,
  aux_sym__sql_block_body_repeat1 = 35,
  aux_sym_object_repeat1 = 36,
  aux_sym_array_repeat1 = 37,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_config] = "config",
  [anon_sym_js] = "js",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_pre_operations] = "pre_operations",
  [anon_sym_post_operations] = "post_operations",
  [anon_sym_input] = "input",
  [anon_sym_DOLLAR_LBRACE] = "${",
  [anon_sym_COMMA] = ",",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_COLON] = ":",
  [sym_property_identifier] = "property_identifier",
  [aux_sym_string_token1] = "string_token1",
  [aux_sym_string_token2] = "string_token2",
  [sym_comment] = "comment",
  [sym_sql_text] = "sql_text",
  [sym_block_sql_text] = "block_sql_text",
  [sym_js_body] = "js_body",
  [sym_js_expression] = "js_expression",
  [sym_source_file] = "source_file",
  [sym_config_block] = "config_block",
  [sym_js_block] = "js_block",
  [sym_pre_operations_block] = "pre_operations_block",
  [sym_post_operations_block] = "post_operations_block",
  [sym_input_block] = "input_block",
  [sym__sql_block_body] = "_sql_block_body",
  [sym_interpolation] = "interpolation",
  [sym_object] = "object",
  [sym_array] = "array",
  [sym_pair] = "pair",
  [sym__value] = "_value",
  [sym_string] = "string",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym__sql_block_body_repeat1] = "_sql_block_body_repeat1",
  [aux_sym_object_repeat1] = "object_repeat1",
  [aux_sym_array_repeat1] = "array_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_config] = anon_sym_config,
  [anon_sym_js] = anon_sym_js,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_pre_operations] = anon_sym_pre_operations,
  [anon_sym_post_operations] = anon_sym_post_operations,
  [anon_sym_input] = anon_sym_input,
  [anon_sym_DOLLAR_LBRACE] = anon_sym_DOLLAR_LBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_property_identifier] = sym_property_identifier,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [aux_sym_string_token2] = aux_sym_string_token2,
  [sym_comment] = sym_comment,
  [sym_sql_text] = sym_sql_text,
  [sym_block_sql_text] = sym_block_sql_text,
  [sym_js_body] = sym_js_body,
  [sym_js_expression] = sym_js_expression,
  [sym_source_file] = sym_source_file,
  [sym_config_block] = sym_config_block,
  [sym_js_block] = sym_js_block,
  [sym_pre_operations_block] = sym_pre_operations_block,
  [sym_post_operations_block] = sym_post_operations_block,
  [sym_input_block] = sym_input_block,
  [sym__sql_block_body] = sym__sql_block_body,
  [sym_interpolation] = sym_interpolation,
  [sym_object] = sym_object,
  [sym_array] = sym_array,
  [sym_pair] = sym_pair,
  [sym__value] = sym__value,
  [sym_string] = sym_string,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym__sql_block_body_repeat1] = aux_sym__sql_block_body_repeat1,
  [aux_sym_object_repeat1] = aux_sym_object_repeat1,
  [aux_sym_array_repeat1] = aux_sym_array_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_config] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_js] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_pre_operations] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_post_operations] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_input] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_property_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_sql_text] = {
    .visible = true,
    .named = true,
  },
  [sym_block_sql_text] = {
    .visible = true,
    .named = true,
  },
  [sym_js_body] = {
    .visible = true,
    .named = true,
  },
  [sym_js_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_config_block] = {
    .visible = true,
    .named = true,
  },
  [sym_js_block] = {
    .visible = true,
    .named = true,
  },
  [sym_pre_operations_block] = {
    .visible = true,
    .named = true,
  },
  [sym_post_operations_block] = {
    .visible = true,
    .named = true,
  },
  [sym_input_block] = {
    .visible = true,
    .named = true,
  },
  [sym__sql_block_body] = {
    .visible = false,
    .named = true,
  },
  [sym_interpolation] = {
    .visible = true,
    .named = true,
  },
  [sym_object] = {
    .visible = true,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym_pair] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__sql_block_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_object_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_key = 1,
  field_value = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_key] = "key",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_key, 0},
    {field_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 19,
  [23] = 23,
  [24] = 24,
  [25] = 24,
  [26] = 26,
  [27] = 27,
  [28] = 27,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 18,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 8,
  [46] = 6,
  [47] = 12,
  [48] = 13,
  [49] = 17,
  [50] = 35,
  [51] = 34,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 57,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 65,
  [70] = 70,
  [71] = 70,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(47);
      ADVANCE_MAP(
        '"', 2,
        '$', 101,
        '\'', 3,
        ',', 61,
        '/', 4,
        ':', 64,
        '[', 62,
        ']', 63,
        'c', 81,
        'i', 77,
        'j', 92,
        'p', 82,
        '{', 52,
        '}', 53,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '\'') ADVANCE(3);
      if (lookahead == ',') ADVANCE(61);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == '}') ADVANCE(53);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (lookahead == '$' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(103);
      if (lookahead == '\\') ADVANCE(44);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '\'') ADVANCE(104);
      if (lookahead == '\\') ADVANCE(45);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(6);
      if (lookahead == '/') ADVANCE(106);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead == '/') ADVANCE(105);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '_') ADVANCE(25);
      END_STATE();
    case 8:
      if (lookahead == '_') ADVANCE(28);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(39);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(40);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(7);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(32);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(33);
      END_STATE();
    case 14:
      if (lookahead == 'f') ADVANCE(16);
      END_STATE();
    case 15:
      if (lookahead == 'g') ADVANCE(48);
      END_STATE();
    case 16:
      if (lookahead == 'i') ADVANCE(15);
      END_STATE();
    case 17:
      if (lookahead == 'i') ADVANCE(26);
      END_STATE();
    case 18:
      if (lookahead == 'i') ADVANCE(27);
      END_STATE();
    case 19:
      if (lookahead == 'n') ADVANCE(29);
      END_STATE();
    case 20:
      if (lookahead == 'n') ADVANCE(14);
      END_STATE();
    case 21:
      if (lookahead == 'n') ADVANCE(36);
      END_STATE();
    case 22:
      if (lookahead == 'n') ADVANCE(37);
      END_STATE();
    case 23:
      if (lookahead == 'o') ADVANCE(20);
      END_STATE();
    case 24:
      if (lookahead == 'o') ADVANCE(35);
      if (lookahead == 'r') ADVANCE(11);
      END_STATE();
    case 25:
      if (lookahead == 'o') ADVANCE(30);
      END_STATE();
    case 26:
      if (lookahead == 'o') ADVANCE(21);
      END_STATE();
    case 27:
      if (lookahead == 'o') ADVANCE(22);
      END_STATE();
    case 28:
      if (lookahead == 'o') ADVANCE(31);
      END_STATE();
    case 29:
      if (lookahead == 'p') ADVANCE(42);
      END_STATE();
    case 30:
      if (lookahead == 'p') ADVANCE(12);
      END_STATE();
    case 31:
      if (lookahead == 'p') ADVANCE(13);
      END_STATE();
    case 32:
      if (lookahead == 'r') ADVANCE(9);
      END_STATE();
    case 33:
      if (lookahead == 'r') ADVANCE(10);
      END_STATE();
    case 34:
      if (lookahead == 's') ADVANCE(50);
      END_STATE();
    case 35:
      if (lookahead == 's') ADVANCE(41);
      END_STATE();
    case 36:
      if (lookahead == 's') ADVANCE(54);
      END_STATE();
    case 37:
      if (lookahead == 's') ADVANCE(56);
      END_STATE();
    case 38:
      if (lookahead == 't') ADVANCE(58);
      END_STATE();
    case 39:
      if (lookahead == 't') ADVANCE(17);
      END_STATE();
    case 40:
      if (lookahead == 't') ADVANCE(18);
      END_STATE();
    case 41:
      if (lookahead == 't') ADVANCE(8);
      END_STATE();
    case 42:
      if (lookahead == 'u') ADVANCE(38);
      END_STATE();
    case 43:
      if (lookahead == '{') ADVANCE(60);
      END_STATE();
    case 44:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 45:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    case 46:
      if (eof) ADVANCE(47);
      if (lookahead == '$') ADVANCE(43);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == 'c') ADVANCE(23);
      if (lookahead == 'i') ADVANCE(19);
      if (lookahead == 'j') ADVANCE(34);
      if (lookahead == 'p') ADVANCE(24);
      if (lookahead == '}') ADVANCE(53);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_config);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_config);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_js);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_js);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_pre_operations);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_pre_operations);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_post_operations);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_post_operations);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_input);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_input);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_DOLLAR_LBRACE);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == '_') ADVANCE(83);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == '_') ADVANCE(86);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 'a') ADVANCE(97);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 'a') ADVANCE(98);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 'e') ADVANCE(65);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 'e') ADVANCE(90);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 'e') ADVANCE(91);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 'f') ADVANCE(74);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 'g') ADVANCE(49);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 'i') ADVANCE(73);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 'i') ADVANCE(84);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 'i') ADVANCE(85);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 'n') ADVANCE(87);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 'n') ADVANCE(72);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 'n') ADVANCE(94);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 'n') ADVANCE(95);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 'o') ADVANCE(78);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 'o') ADVANCE(93);
      if (lookahead == 'r') ADVANCE(69);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 'o') ADVANCE(88);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 'o') ADVANCE(79);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 'o') ADVANCE(80);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 'o') ADVANCE(89);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 'p') ADVANCE(100);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 'p') ADVANCE(70);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 'p') ADVANCE(71);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 'r') ADVANCE(67);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 'r') ADVANCE(68);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 's') ADVANCE(51);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 's') ADVANCE(99);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 's') ADVANCE(55);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 's') ADVANCE(57);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 't') ADVANCE(59);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 't') ADVANCE(75);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 't') ADVANCE(76);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 't') ADVANCE(66);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 'u') ADVANCE(96);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == '{') ADVANCE(60);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(aux_sym_string_token1);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(aux_sym_string_token2);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(106);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 46, .external_lex_state = 2},
  [2] = {.lex_state = 46, .external_lex_state = 2},
  [3] = {.lex_state = 46, .external_lex_state = 2},
  [4] = {.lex_state = 46, .external_lex_state = 2},
  [5] = {.lex_state = 46, .external_lex_state = 2},
  [6] = {.lex_state = 46, .external_lex_state = 2},
  [7] = {.lex_state = 46, .external_lex_state = 2},
  [8] = {.lex_state = 46, .external_lex_state = 2},
  [9] = {.lex_state = 46, .external_lex_state = 2},
  [10] = {.lex_state = 46, .external_lex_state = 2},
  [11] = {.lex_state = 46, .external_lex_state = 2},
  [12] = {.lex_state = 46, .external_lex_state = 2},
  [13] = {.lex_state = 46, .external_lex_state = 2},
  [14] = {.lex_state = 46, .external_lex_state = 2},
  [15] = {.lex_state = 46, .external_lex_state = 2},
  [16] = {.lex_state = 0, .external_lex_state = 3},
  [17] = {.lex_state = 46, .external_lex_state = 2},
  [18] = {.lex_state = 46, .external_lex_state = 2},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 0, .external_lex_state = 3},
  [21] = {.lex_state = 0, .external_lex_state = 3},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 0, .external_lex_state = 3},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 0, .external_lex_state = 3},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 46, .external_lex_state = 4},
  [30] = {.lex_state = 46, .external_lex_state = 4},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 46, .external_lex_state = 4},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 46, .external_lex_state = 4},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 46, .external_lex_state = 4},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0, .external_lex_state = 5},
  [57] = {.lex_state = 0, .external_lex_state = 5},
  [58] = {.lex_state = 0, .external_lex_state = 5},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_config] = ACTIONS(1),
    [anon_sym_js] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_pre_operations] = ACTIONS(1),
    [anon_sym_post_operations] = ACTIONS(1),
    [anon_sym_input] = ACTIONS(1),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_property_identifier] = ACTIONS(1),
    [aux_sym_string_token1] = ACTIONS(1),
    [aux_sym_string_token2] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_sql_text] = ACTIONS(1),
    [sym_block_sql_text] = ACTIONS(1),
    [sym_js_body] = ACTIONS(1),
    [sym_js_expression] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(63),
    [sym_config_block] = STATE(2),
    [sym_js_block] = STATE(2),
    [sym_pre_operations_block] = STATE(2),
    [sym_post_operations_block] = STATE(2),
    [sym_input_block] = STATE(2),
    [sym_interpolation] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_config] = ACTIONS(7),
    [anon_sym_js] = ACTIONS(9),
    [anon_sym_pre_operations] = ACTIONS(11),
    [anon_sym_post_operations] = ACTIONS(13),
    [anon_sym_input] = ACTIONS(15),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
    [sym_sql_text] = ACTIONS(19),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_config,
    ACTIONS(9), 1,
      anon_sym_js,
    ACTIONS(11), 1,
      anon_sym_pre_operations,
    ACTIONS(13), 1,
      anon_sym_post_operations,
    ACTIONS(15), 1,
      anon_sym_input,
    ACTIONS(17), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    ACTIONS(23), 1,
      sym_sql_text,
    STATE(3), 7,
      sym_config_block,
      sym_js_block,
      sym_pre_operations_block,
      sym_post_operations_block,
      sym_input_block,
      sym_interpolation,
      aux_sym_source_file_repeat1,
  [37] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
    ACTIONS(27), 1,
      anon_sym_config,
    ACTIONS(30), 1,
      anon_sym_js,
    ACTIONS(33), 1,
      anon_sym_pre_operations,
    ACTIONS(36), 1,
      anon_sym_post_operations,
    ACTIONS(39), 1,
      anon_sym_input,
    ACTIONS(42), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(45), 1,
      sym_sql_text,
    STATE(3), 7,
      sym_config_block,
      sym_js_block,
      sym_pre_operations_block,
      sym_post_operations_block,
      sym_input_block,
      sym_interpolation,
      aux_sym_source_file_repeat1,
  [74] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(48), 8,
      sym_sql_text,
      ts_builtin_sym_end,
      anon_sym_config,
      anon_sym_js,
      anon_sym_pre_operations,
      anon_sym_post_operations,
      anon_sym_input,
      anon_sym_DOLLAR_LBRACE,
  [88] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(50), 8,
      sym_sql_text,
      ts_builtin_sym_end,
      anon_sym_config,
      anon_sym_js,
      anon_sym_pre_operations,
      anon_sym_post_operations,
      anon_sym_input,
      anon_sym_DOLLAR_LBRACE,
  [102] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(52), 8,
      sym_sql_text,
      ts_builtin_sym_end,
      anon_sym_config,
      anon_sym_js,
      anon_sym_pre_operations,
      anon_sym_post_operations,
      anon_sym_input,
      anon_sym_DOLLAR_LBRACE,
  [116] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(54), 8,
      sym_sql_text,
      ts_builtin_sym_end,
      anon_sym_config,
      anon_sym_js,
      anon_sym_pre_operations,
      anon_sym_post_operations,
      anon_sym_input,
      anon_sym_DOLLAR_LBRACE,
  [130] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(56), 8,
      sym_sql_text,
      ts_builtin_sym_end,
      anon_sym_config,
      anon_sym_js,
      anon_sym_pre_operations,
      anon_sym_post_operations,
      anon_sym_input,
      anon_sym_DOLLAR_LBRACE,
  [144] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(58), 8,
      sym_sql_text,
      ts_builtin_sym_end,
      anon_sym_config,
      anon_sym_js,
      anon_sym_pre_operations,
      anon_sym_post_operations,
      anon_sym_input,
      anon_sym_DOLLAR_LBRACE,
  [158] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(60), 8,
      sym_sql_text,
      ts_builtin_sym_end,
      anon_sym_config,
      anon_sym_js,
      anon_sym_pre_operations,
      anon_sym_post_operations,
      anon_sym_input,
      anon_sym_DOLLAR_LBRACE,
  [172] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(62), 8,
      sym_sql_text,
      ts_builtin_sym_end,
      anon_sym_config,
      anon_sym_js,
      anon_sym_pre_operations,
      anon_sym_post_operations,
      anon_sym_input,
      anon_sym_DOLLAR_LBRACE,
  [186] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(64), 8,
      sym_sql_text,
      ts_builtin_sym_end,
      anon_sym_config,
      anon_sym_js,
      anon_sym_pre_operations,
      anon_sym_post_operations,
      anon_sym_input,
      anon_sym_DOLLAR_LBRACE,
  [200] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(66), 8,
      sym_sql_text,
      ts_builtin_sym_end,
      anon_sym_config,
      anon_sym_js,
      anon_sym_pre_operations,
      anon_sym_post_operations,
      anon_sym_input,
      anon_sym_DOLLAR_LBRACE,
  [214] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 8,
      sym_sql_text,
      ts_builtin_sym_end,
      anon_sym_config,
      anon_sym_js,
      anon_sym_pre_operations,
      anon_sym_post_operations,
      anon_sym_input,
      anon_sym_DOLLAR_LBRACE,
  [228] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 8,
      sym_sql_text,
      ts_builtin_sym_end,
      anon_sym_config,
      anon_sym_js,
      anon_sym_pre_operations,
      anon_sym_post_operations,
      anon_sym_input,
      anon_sym_DOLLAR_LBRACE,
  [242] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(72), 1,
      anon_sym_LBRACE,
    ACTIONS(74), 1,
      anon_sym_COMMA,
    ACTIONS(76), 1,
      anon_sym_LBRACK,
    ACTIONS(78), 1,
      anon_sym_RBRACK,
    ACTIONS(80), 1,
      sym_js_expression,
    STATE(38), 3,
      sym_object,
      sym_array,
      sym__value,
  [266] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 8,
      sym_sql_text,
      ts_builtin_sym_end,
      anon_sym_config,
      anon_sym_js,
      anon_sym_pre_operations,
      anon_sym_post_operations,
      anon_sym_input,
      anon_sym_DOLLAR_LBRACE,
  [280] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(84), 8,
      sym_sql_text,
      ts_builtin_sym_end,
      anon_sym_config,
      anon_sym_js,
      anon_sym_pre_operations,
      anon_sym_post_operations,
      anon_sym_input,
      anon_sym_DOLLAR_LBRACE,
  [294] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 1,
      anon_sym_RBRACE,
    ACTIONS(88), 1,
      anon_sym_COMMA,
    ACTIONS(90), 1,
      sym_property_identifier,
    STATE(35), 1,
      sym_pair,
    STATE(68), 1,
      sym_string,
    ACTIONS(92), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
  [317] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(72), 1,
      anon_sym_LBRACE,
    ACTIONS(76), 1,
      anon_sym_LBRACK,
    ACTIONS(94), 1,
      anon_sym_RBRACK,
    ACTIONS(96), 1,
      sym_js_expression,
    STATE(53), 3,
      sym_object,
      sym_array,
      sym__value,
  [338] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(72), 1,
      anon_sym_LBRACE,
    ACTIONS(76), 1,
      anon_sym_LBRACK,
    ACTIONS(96), 1,
      sym_js_expression,
    ACTIONS(98), 1,
      anon_sym_RBRACK,
    STATE(53), 3,
      sym_object,
      sym_array,
      sym__value,
  [359] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 1,
      sym_property_identifier,
    ACTIONS(100), 1,
      anon_sym_RBRACE,
    ACTIONS(102), 1,
      anon_sym_COMMA,
    STATE(50), 1,
      sym_pair,
    STATE(68), 1,
      sym_string,
    ACTIONS(92), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
  [382] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(72), 1,
      anon_sym_LBRACE,
    ACTIONS(76), 1,
      anon_sym_LBRACK,
    ACTIONS(96), 1,
      sym_js_expression,
    STATE(53), 3,
      sym_object,
      sym_array,
      sym__value,
  [400] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 1,
      sym_property_identifier,
    ACTIONS(104), 1,
      anon_sym_RBRACE,
    STATE(61), 1,
      sym_pair,
    STATE(68), 1,
      sym_string,
    ACTIONS(92), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
  [420] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 1,
      sym_property_identifier,
    ACTIONS(106), 1,
      anon_sym_RBRACE,
    STATE(61), 1,
      sym_pair,
    STATE(68), 1,
      sym_string,
    ACTIONS(92), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
  [440] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(72), 1,
      anon_sym_LBRACE,
    ACTIONS(76), 1,
      anon_sym_LBRACK,
    ACTIONS(108), 1,
      sym_js_expression,
    STATE(55), 3,
      sym_object,
      sym_array,
      sym__value,
  [458] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 1,
      sym_property_identifier,
    ACTIONS(110), 1,
      anon_sym_RBRACE,
    STATE(61), 1,
      sym_pair,
    STATE(68), 1,
      sym_string,
    ACTIONS(92), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
  [478] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 1,
      sym_property_identifier,
    ACTIONS(112), 1,
      anon_sym_RBRACE,
    STATE(61), 1,
      sym_pair,
    STATE(68), 1,
      sym_string,
    ACTIONS(92), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
  [498] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 1,
      anon_sym_RBRACE,
    ACTIONS(116), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(118), 1,
      sym_block_sql_text,
    STATE(32), 2,
      sym_interpolation,
      aux_sym__sql_block_body_repeat1,
  [515] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(116), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(120), 1,
      anon_sym_RBRACE,
    ACTIONS(122), 1,
      sym_block_sql_text,
    STATE(29), 2,
      sym_interpolation,
      aux_sym__sql_block_body_repeat1,
  [532] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 1,
      sym_property_identifier,
    STATE(61), 1,
      sym_pair,
    STATE(68), 1,
      sym_string,
    ACTIONS(92), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
  [549] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(124), 1,
      anon_sym_RBRACE,
    ACTIONS(126), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(129), 1,
      sym_block_sql_text,
    STATE(32), 2,
      sym_interpolation,
      aux_sym__sql_block_body_repeat1,
  [566] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(84), 3,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [575] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(106), 1,
      anon_sym_RBRACE,
    ACTIONS(132), 1,
      anon_sym_COMMA,
    STATE(36), 1,
      aux_sym_object_repeat1,
  [588] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(134), 1,
      anon_sym_RBRACE,
    ACTIONS(136), 1,
      anon_sym_COMMA,
    STATE(51), 1,
      aux_sym_object_repeat1,
  [601] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 1,
      anon_sym_RBRACE,
    ACTIONS(140), 1,
      anon_sym_COMMA,
    STATE(36), 1,
      aux_sym_object_repeat1,
  [614] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 3,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [623] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(145), 1,
      anon_sym_COMMA,
    ACTIONS(147), 1,
      anon_sym_RBRACK,
    STATE(40), 1,
      aux_sym_array_repeat1,
  [636] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 3,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [645] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 1,
      anon_sym_RBRACK,
    ACTIONS(151), 1,
      anon_sym_COMMA,
    STATE(42), 1,
      aux_sym_array_repeat1,
  [658] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 3,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [667] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 1,
      anon_sym_COMMA,
    ACTIONS(158), 1,
      anon_sym_RBRACK,
    STATE(42), 1,
      aux_sym_array_repeat1,
  [680] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(160), 3,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [689] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(62), 1,
      sym_string,
    ACTIONS(92), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
  [700] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(56), 3,
      sym_block_sql_text,
      anon_sym_RBRACE,
      anon_sym_DOLLAR_LBRACE,
  [709] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(52), 3,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [718] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(64), 3,
      sym_block_sql_text,
      anon_sym_RBRACE,
      anon_sym_DOLLAR_LBRACE,
  [727] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(66), 3,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [736] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 3,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [745] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(162), 1,
      anon_sym_RBRACE,
    ACTIONS(164), 1,
      anon_sym_COMMA,
    STATE(34), 1,
      aux_sym_object_repeat1,
  [758] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 1,
      anon_sym_RBRACE,
    ACTIONS(166), 1,
      anon_sym_COMMA,
    STATE(36), 1,
      aux_sym_object_repeat1,
  [771] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(168), 1,
      anon_sym_LBRACE,
    STATE(7), 1,
      sym__sql_block_body,
  [781] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(158), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [789] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(168), 1,
      anon_sym_LBRACE,
    STATE(5), 1,
      sym__sql_block_body,
  [799] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(170), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [807] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(172), 1,
      anon_sym_RBRACE,
    ACTIONS(174), 1,
      sym_js_body,
  [817] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(176), 1,
      anon_sym_RBRACE,
    ACTIONS(178), 1,
      sym_js_body,
  [827] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(180), 1,
      anon_sym_RBRACE,
    ACTIONS(182), 1,
      sym_js_body,
  [837] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(184), 2,
      anon_sym_LBRACE,
      anon_sym_COLON,
  [845] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 1,
      anon_sym_LBRACE,
    STATE(4), 1,
      sym_object,
  [855] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [863] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(168), 1,
      anon_sym_LBRACE,
    STATE(11), 1,
      sym__sql_block_body,
  [873] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 1,
      ts_builtin_sym_end,
  [880] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(190), 1,
      anon_sym_LBRACE,
  [887] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(134), 1,
      anon_sym_RBRACE,
  [894] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(192), 1,
      anon_sym_RBRACE,
  [901] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 1,
      anon_sym_RBRACK,
  [908] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(194), 1,
      anon_sym_COLON,
  [915] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(162), 1,
      anon_sym_RBRACE,
  [922] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(196), 1,
      anon_sym_RBRACE,
  [929] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(198), 1,
      anon_sym_RBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 37,
  [SMALL_STATE(4)] = 74,
  [SMALL_STATE(5)] = 88,
  [SMALL_STATE(6)] = 102,
  [SMALL_STATE(7)] = 116,
  [SMALL_STATE(8)] = 130,
  [SMALL_STATE(9)] = 144,
  [SMALL_STATE(10)] = 158,
  [SMALL_STATE(11)] = 172,
  [SMALL_STATE(12)] = 186,
  [SMALL_STATE(13)] = 200,
  [SMALL_STATE(14)] = 214,
  [SMALL_STATE(15)] = 228,
  [SMALL_STATE(16)] = 242,
  [SMALL_STATE(17)] = 266,
  [SMALL_STATE(18)] = 280,
  [SMALL_STATE(19)] = 294,
  [SMALL_STATE(20)] = 317,
  [SMALL_STATE(21)] = 338,
  [SMALL_STATE(22)] = 359,
  [SMALL_STATE(23)] = 382,
  [SMALL_STATE(24)] = 400,
  [SMALL_STATE(25)] = 420,
  [SMALL_STATE(26)] = 440,
  [SMALL_STATE(27)] = 458,
  [SMALL_STATE(28)] = 478,
  [SMALL_STATE(29)] = 498,
  [SMALL_STATE(30)] = 515,
  [SMALL_STATE(31)] = 532,
  [SMALL_STATE(32)] = 549,
  [SMALL_STATE(33)] = 566,
  [SMALL_STATE(34)] = 575,
  [SMALL_STATE(35)] = 588,
  [SMALL_STATE(36)] = 601,
  [SMALL_STATE(37)] = 614,
  [SMALL_STATE(38)] = 623,
  [SMALL_STATE(39)] = 636,
  [SMALL_STATE(40)] = 645,
  [SMALL_STATE(41)] = 658,
  [SMALL_STATE(42)] = 667,
  [SMALL_STATE(43)] = 680,
  [SMALL_STATE(44)] = 689,
  [SMALL_STATE(45)] = 700,
  [SMALL_STATE(46)] = 709,
  [SMALL_STATE(47)] = 718,
  [SMALL_STATE(48)] = 727,
  [SMALL_STATE(49)] = 736,
  [SMALL_STATE(50)] = 745,
  [SMALL_STATE(51)] = 758,
  [SMALL_STATE(52)] = 771,
  [SMALL_STATE(53)] = 781,
  [SMALL_STATE(54)] = 789,
  [SMALL_STATE(55)] = 799,
  [SMALL_STATE(56)] = 807,
  [SMALL_STATE(57)] = 817,
  [SMALL_STATE(58)] = 827,
  [SMALL_STATE(59)] = 837,
  [SMALL_STATE(60)] = 845,
  [SMALL_STATE(61)] = 855,
  [SMALL_STATE(62)] = 863,
  [SMALL_STATE(63)] = 873,
  [SMALL_STATE(64)] = 880,
  [SMALL_STATE(65)] = 887,
  [SMALL_STATE(66)] = 894,
  [SMALL_STATE(67)] = 901,
  [SMALL_STATE(68)] = 908,
  [SMALL_STATE(69)] = 915,
  [SMALL_STATE(70)] = 922,
  [SMALL_STATE(71)] = 929,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(64),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(57),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_config_block, 2, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pre_operations_block, 2, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 2, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_post_operations_block, 2, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interpolation, 2, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_js_block, 3, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__sql_block_body, 2, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_input_block, 3, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interpolation, 3, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 3, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_js_block, 4, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__sql_block_body, 3, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 4, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 5, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__sql_block_body_repeat1, 2, 0, 0),
  [126] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__sql_block_body_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [129] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__sql_block_body_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_object_repeat1, 2, 0, 0),
  [140] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_object_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 4, 0, 0),
  [155] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 5, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pair, 3, 0, 1),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1, 0, 0),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [188] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_sql_text = 0,
  ts_external_token_block_sql_text = 1,
  ts_external_token_js_body = 2,
  ts_external_token_js_expression = 3,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_sql_text] = sym_sql_text,
  [ts_external_token_block_sql_text] = sym_block_sql_text,
  [ts_external_token_js_body] = sym_js_body,
  [ts_external_token_js_expression] = sym_js_expression,
};

static const bool ts_external_scanner_states[6][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_sql_text] = true,
    [ts_external_token_block_sql_text] = true,
    [ts_external_token_js_body] = true,
    [ts_external_token_js_expression] = true,
  },
  [2] = {
    [ts_external_token_sql_text] = true,
  },
  [3] = {
    [ts_external_token_js_expression] = true,
  },
  [4] = {
    [ts_external_token_block_sql_text] = true,
  },
  [5] = {
    [ts_external_token_js_body] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_sqlx_external_scanner_create(void);
void tree_sitter_sqlx_external_scanner_destroy(void *);
bool tree_sitter_sqlx_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_sqlx_external_scanner_serialize(void *, char *);
void tree_sitter_sqlx_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_sqlx(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_sqlx_external_scanner_create,
      tree_sitter_sqlx_external_scanner_destroy,
      tree_sitter_sqlx_external_scanner_scan,
      tree_sitter_sqlx_external_scanner_serialize,
      tree_sitter_sqlx_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
