/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 74
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 40
#define ALIAS_COUNT 0
#define TOKEN_COUNT 22
#define EXTERNAL_TOKEN_COUNT 4
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_config = 1,
  anon_sym_js = 2,
  anon_sym_LBRACE = 3,
  anon_sym_RBRACE = 4,
  anon_sym_pre_operations = 5,
  anon_sym_post_operations = 6,
  anon_sym_incremental_where = 7,
  anon_sym_input = 8,
  anon_sym_DOLLAR_LBRACE = 9,
  anon_sym_COMMA = 10,
  anon_sym_LBRACK = 11,
  anon_sym_RBRACK = 12,
  anon_sym_COLON = 13,
  sym_property_identifier = 14,
  aux_sym_string_token1 = 15,
  aux_sym_string_token2 = 16,
  sym_comment = 17,
  sym_sql_text = 18,
  sym_block_sql_text = 19,
  sym_js_body = 20,
  sym_js_expression = 21,
  sym_source_file = 22,
  sym_config_block = 23,
  sym_js_block = 24,
  sym_pre_operations_block = 25,
  sym_post_operations_block = 26,
  sym_incremental_where_block = 27,
  sym_input_block = 28,
  sym__sql_block_body = 29,
  sym_interpolation = 30,
  sym_object = 31,
  sym_array = 32,
  sym_pair = 33,
  sym__value = 34,
  sym_string = 35,
  aux_sym_source_file_repeat1 = 36,
  aux_sym__sql_block_body_repeat1 = 37,
  aux_sym_object_repeat1 = 38,
  aux_sym_array_repeat1 = 39,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_config] = "config",
  [anon_sym_js] = "js",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_pre_operations] = "pre_operations",
  [anon_sym_post_operations] = "post_operations",
  [anon_sym_incremental_where] = "incremental_where",
  [anon_sym_input] = "input",
  [anon_sym_DOLLAR_LBRACE] = "${",
  [anon_sym_COMMA] = ",",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_COLON] = ":",
  [sym_property_identifier] = "property_identifier",
  [aux_sym_string_token1] = "string_token1",
  [aux_sym_string_token2] = "string_token2",
  [sym_comment] = "comment",
  [sym_sql_text] = "sql_text",
  [sym_block_sql_text] = "block_sql_text",
  [sym_js_body] = "js_body",
  [sym_js_expression] = "js_expression",
  [sym_source_file] = "source_file",
  [sym_config_block] = "config_block",
  [sym_js_block] = "js_block",
  [sym_pre_operations_block] = "pre_operations_block",
  [sym_post_operations_block] = "post_operations_block",
  [sym_incremental_where_block] = "incremental_where_block",
  [sym_input_block] = "input_block",
  [sym__sql_block_body] = "_sql_block_body",
  [sym_interpolation] = "interpolation",
  [sym_object] = "object",
  [sym_array] = "array",
  [sym_pair] = "pair",
  [sym__value] = "_value",
  [sym_string] = "string",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym__sql_block_body_repeat1] = "_sql_block_body_repeat1",
  [aux_sym_object_repeat1] = "object_repeat1",
  [aux_sym_array_repeat1] = "array_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_config] = anon_sym_config,
  [anon_sym_js] = anon_sym_js,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_pre_operations] = anon_sym_pre_operations,
  [anon_sym_post_operations] = anon_sym_post_operations,
  [anon_sym_incremental_where] = anon_sym_incremental_where,
  [anon_sym_input] = anon_sym_input,
  [anon_sym_DOLLAR_LBRACE] = anon_sym_DOLLAR_LBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_property_identifier] = sym_property_identifier,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [aux_sym_string_token2] = aux_sym_string_token2,
  [sym_comment] = sym_comment,
  [sym_sql_text] = sym_sql_text,
  [sym_block_sql_text] = sym_block_sql_text,
  [sym_js_body] = sym_js_body,
  [sym_js_expression] = sym_js_expression,
  [sym_source_file] = sym_source_file,
  [sym_config_block] = sym_config_block,
  [sym_js_block] = sym_js_block,
  [sym_pre_operations_block] = sym_pre_operations_block,
  [sym_post_operations_block] = sym_post_operations_block,
  [sym_incremental_where_block] = sym_incremental_where_block,
  [sym_input_block] = sym_input_block,
  [sym__sql_block_body] = sym__sql_block_body,
  [sym_interpolation] = sym_interpolation,
  [sym_object] = sym_object,
  [sym_array] = sym_array,
  [sym_pair] = sym_pair,
  [sym__value] = sym__value,
  [sym_string] = sym_string,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym__sql_block_body_repeat1] = aux_sym__sql_block_body_repeat1,
  [aux_sym_object_repeat1] = aux_sym_object_repeat1,
  [aux_sym_array_repeat1] = aux_sym_array_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_config] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_js] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_pre_operations] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_post_operations] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_incremental_where] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_input] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_property_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_sql_text] = {
    .visible = true,
    .named = true,
  },
  [sym_block_sql_text] = {
    .visible = true,
    .named = true,
  },
  [sym_js_body] = {
    .visible = true,
    .named = true,
  },
  [sym_js_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_config_block] = {
    .visible = true,
    .named = true,
  },
  [sym_js_block] = {
    .visible = true,
    .named = true,
  },
  [sym_pre_operations_block] = {
    .visible = true,
    .named = true,
  },
  [sym_post_operations_block] = {
    .visible = true,
    .named = true,
  },
  [sym_incremental_where_block] = {
    .visible = true,
    .named = true,
  },
  [sym_input_block] = {
    .visible = true,
    .named = true,
  },
  [sym__sql_block_body] = {
    .visible = false,
    .named = true,
  },
  [sym_interpolation] = {
    .visible = true,
    .named = true,
  },
  [sym_object] = {
    .visible = true,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym_pair] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__sql_block_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_object_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_key = 1,
  field_value = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_key] = "key",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_key, 0},
    {field_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 20,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 25,
  [29] = 26,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 34,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 8,
  [45] = 10,
  [46] = 13,
  [47] = 4,
  [48] = 15,
  [49] = 18,
  [50] = 50,
  [51] = 36,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 58,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 65,
  [71] = 71,
  [72] = 72,
  [73] = 71,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(61);
      ADVANCE_MAP(
        '"', 2,
        '$', 131,
        '\'', 3,
        ',', 77,
        '/', 4,
        ':', 80,
        '[', 78,
        ']', 79,
        'c', 109,
        'i', 103,
        'j', 120,
        'p', 110,
        '{', 66,
        '}', 67,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(132);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '\'') ADVANCE(3);
      if (lookahead == ',') ADVANCE(77);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == '}') ADVANCE(67);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (lookahead == '$' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(132);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(133);
      if (lookahead == '\\') ADVANCE(58);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '\'') ADVANCE(134);
      if (lookahead == '\\') ADVANCE(59);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(6);
      if (lookahead == '/') ADVANCE(136);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead == '/') ADVANCE(135);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '_') ADVANCE(56);
      END_STATE();
    case 8:
      if (lookahead == '_') ADVANCE(34);
      END_STATE();
    case 9:
      if (lookahead == '_') ADVANCE(39);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(27);
      END_STATE();
    case 11:
      if (lookahead == 'a') ADVANCE(51);
      END_STATE();
    case 12:
      if (lookahead == 'a') ADVANCE(53);
      END_STATE();
    case 13:
      if (lookahead == 'c') ADVANCE(43);
      if (lookahead == 'p') ADVANCE(55);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(8);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(28);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(72);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(42);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(32);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(44);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(45);
      END_STATE();
    case 21:
      if (lookahead == 'f') ADVANCE(24);
      END_STATE();
    case 22:
      if (lookahead == 'g') ADVANCE(62);
      END_STATE();
    case 23:
      if (lookahead == 'h') ADVANCE(19);
      END_STATE();
    case 24:
      if (lookahead == 'i') ADVANCE(22);
      END_STATE();
    case 25:
      if (lookahead == 'i') ADVANCE(37);
      END_STATE();
    case 26:
      if (lookahead == 'i') ADVANCE(38);
      END_STATE();
    case 27:
      if (lookahead == 'l') ADVANCE(7);
      END_STATE();
    case 28:
      if (lookahead == 'm') ADVANCE(18);
      END_STATE();
    case 29:
      if (lookahead == 'n') ADVANCE(13);
      END_STATE();
    case 30:
      if (lookahead == 'n') ADVANCE(21);
      END_STATE();
    case 31:
      if (lookahead == 'n') ADVANCE(48);
      END_STATE();
    case 32:
      if (lookahead == 'n') ADVANCE(52);
      END_STATE();
    case 33:
      if (lookahead == 'n') ADVANCE(49);
      END_STATE();
    case 34:
      if (lookahead == 'o') ADVANCE(40);
      END_STATE();
    case 35:
      if (lookahead == 'o') ADVANCE(30);
      END_STATE();
    case 36:
      if (lookahead == 'o') ADVANCE(47);
      if (lookahead == 'r') ADVANCE(14);
      END_STATE();
    case 37:
      if (lookahead == 'o') ADVANCE(31);
      END_STATE();
    case 38:
      if (lookahead == 'o') ADVANCE(33);
      END_STATE();
    case 39:
      if (lookahead == 'o') ADVANCE(41);
      END_STATE();
    case 40:
      if (lookahead == 'p') ADVANCE(17);
      END_STATE();
    case 41:
      if (lookahead == 'p') ADVANCE(20);
      END_STATE();
    case 42:
      if (lookahead == 'r') ADVANCE(11);
      END_STATE();
    case 43:
      if (lookahead == 'r') ADVANCE(15);
      END_STATE();
    case 44:
      if (lookahead == 'r') ADVANCE(16);
      END_STATE();
    case 45:
      if (lookahead == 'r') ADVANCE(12);
      END_STATE();
    case 46:
      if (lookahead == 's') ADVANCE(64);
      END_STATE();
    case 47:
      if (lookahead == 's') ADVANCE(54);
      END_STATE();
    case 48:
      if (lookahead == 's') ADVANCE(68);
      END_STATE();
    case 49:
      if (lookahead == 's') ADVANCE(70);
      END_STATE();
    case 50:
      if (lookahead == 't') ADVANCE(74);
      END_STATE();
    case 51:
      if (lookahead == 't') ADVANCE(25);
      END_STATE();
    case 52:
      if (lookahead == 't') ADVANCE(10);
      END_STATE();
    case 53:
      if (lookahead == 't') ADVANCE(26);
      END_STATE();
    case 54:
      if (lookahead == 't') ADVANCE(9);
      END_STATE();
    case 55:
      if (lookahead == 'u') ADVANCE(50);
      END_STATE();
    case 56:
      if (lookahead == 'w') ADVANCE(23);
      END_STATE();
    case 57:
      if (lookahead == '{') ADVANCE(76);
      END_STATE();
    case 58:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 59:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    case 60:
      if (eof) ADVANCE(61);
      if (lookahead == '$') ADVANCE(57);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == 'c') ADVANCE(35);
      if (lookahead == 'i') ADVANCE(29);
      if (lookahead == 'j') ADVANCE(46);
      if (lookahead == 'p') ADVANCE(36);
      if (lookahead == '}') ADVANCE(67);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(60);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_config);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_config);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(132);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_js);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_js);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(132);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_pre_operations);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_pre_operations);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(132);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_post_operations);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_post_operations);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(132);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_incremental_where);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_incremental_where);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(132);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_input);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_input);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(132);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_DOLLAR_LBRACE);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == '_') ADVANCE(130);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(132);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == '_') ADVANCE(108);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(132);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == '_') ADVANCE(113);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(132);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 'a') ADVANCE(101);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(132);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 'a') ADVANCE(125);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(132);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 'a') ADVANCE(127);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(132);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 'c') ADVANCE(117);
      if (lookahead == 'p') ADVANCE(129);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(132);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 'e') ADVANCE(82);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(132);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 'e') ADVANCE(102);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(132);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 'e') ADVANCE(73);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(132);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 'e') ADVANCE(116);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(132);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 'e') ADVANCE(106);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(132);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 'e') ADVANCE(118);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(132);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 'e') ADVANCE(119);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(132);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 'f') ADVANCE(98);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(132);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 'g') ADVANCE(63);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(132);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 'h') ADVANCE(93);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(132);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 'i') ADVANCE(96);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(132);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 'i') ADVANCE(111);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(132);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 'i') ADVANCE(112);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(132);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 'l') ADVANCE(81);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(132);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 'm') ADVANCE(92);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(132);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 'n') ADVANCE(87);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(132);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 'n') ADVANCE(95);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(132);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 'n') ADVANCE(122);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(132);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 'n') ADVANCE(126);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(132);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 'n') ADVANCE(123);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(132);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 'o') ADVANCE(114);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(132);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 'o') ADVANCE(104);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(132);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 'o') ADVANCE(121);
      if (lookahead == 'r') ADVANCE(88);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(132);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 'o') ADVANCE(105);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(132);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 'o') ADVANCE(107);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(132);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 'o') ADVANCE(115);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(132);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 'p') ADVANCE(91);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(132);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 'p') ADVANCE(94);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(132);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 'r') ADVANCE(85);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(132);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 'r') ADVANCE(89);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(132);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 'r') ADVANCE(90);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(132);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 'r') ADVANCE(86);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(132);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 's') ADVANCE(65);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(132);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 's') ADVANCE(128);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(132);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 's') ADVANCE(69);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(132);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 's') ADVANCE(71);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(132);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 't') ADVANCE(75);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(132);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 't') ADVANCE(99);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(132);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 't') ADVANCE(84);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(132);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 't') ADVANCE(100);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(132);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 't') ADVANCE(83);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(132);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 'u') ADVANCE(124);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(132);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == 'w') ADVANCE(97);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(132);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == '{') ADVANCE(76);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(132);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(sym_property_identifier);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(132);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(aux_sym_string_token1);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(aux_sym_string_token2);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(136);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 60, .external_lex_state = 2},
  [2] = {.lex_state = 60, .external_lex_state = 2},
  [3] = {.lex_state = 60, .external_lex_state = 2},
  [4] = {.lex_state = 60, .external_lex_state = 2},
  [5] = {.lex_state = 60, .external_lex_state = 2},
  [6] = {.lex_state = 60, .external_lex_state = 2},
  [7] = {.lex_state = 60, .external_lex_state = 2},
  [8] = {.lex_state = 60, .external_lex_state = 2},
  [9] = {.lex_state = 60, .external_lex_state = 2},
  [10] = {.lex_state = 60, .external_lex_state = 2},
  [11] = {.lex_state = 60, .external_lex_state = 2},
  [12] = {.lex_state = 60, .external_lex_state = 2},
  [13] = {.lex_state = 60, .external_lex_state = 2},
  [14] = {.lex_state = 60, .external_lex_state = 2},
  [15] = {.lex_state = 60, .external_lex_state = 2},
  [16] = {.lex_state = 60, .external_lex_state = 2},
  [17] = {.lex_state = 60, .external_lex_state = 2},
  [18] = {.lex_state = 60, .external_lex_state = 2},
  [19] = {.lex_state = 0, .external_lex_state = 3},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 0, .external_lex_state = 3},
  [23] = {.lex_state = 0, .external_lex_state = 3},
  [24] = {.lex_state = 0, .external_lex_state = 3},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 0, .external_lex_state = 3},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 60, .external_lex_state = 4},
  [31] = {.lex_state = 60, .external_lex_state = 4},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 60, .external_lex_state = 4},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 60, .external_lex_state = 4},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 60, .external_lex_state = 4},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0, .external_lex_state = 5},
  [59] = {.lex_state = 0, .external_lex_state = 5},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0, .external_lex_state = 5},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_config] = ACTIONS(1),
    [anon_sym_js] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_pre_operations] = ACTIONS(1),
    [anon_sym_post_operations] = ACTIONS(1),
    [anon_sym_incremental_where] = ACTIONS(1),
    [anon_sym_input] = ACTIONS(1),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_property_identifier] = ACTIONS(1),
    [aux_sym_string_token1] = ACTIONS(1),
    [aux_sym_string_token2] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_sql_text] = ACTIONS(1),
    [sym_block_sql_text] = ACTIONS(1),
    [sym_js_body] = ACTIONS(1),
    [sym_js_expression] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(66),
    [sym_config_block] = STATE(2),
    [sym_js_block] = STATE(2),
    [sym_pre_operations_block] = STATE(2),
    [sym_post_operations_block] = STATE(2),
    [sym_incremental_where_block] = STATE(2),
    [sym_input_block] = STATE(2),
    [sym_interpolation] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_config] = ACTIONS(7),
    [anon_sym_js] = ACTIONS(9),
    [anon_sym_pre_operations] = ACTIONS(11),
    [anon_sym_post_operations] = ACTIONS(13),
    [anon_sym_incremental_where] = ACTIONS(15),
    [anon_sym_input] = ACTIONS(17),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(19),
    [sym_comment] = ACTIONS(3),
    [sym_sql_text] = ACTIONS(21),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_config,
    ACTIONS(9), 1,
      anon_sym_js,
    ACTIONS(11), 1,
      anon_sym_pre_operations,
    ACTIONS(13), 1,
      anon_sym_post_operations,
    ACTIONS(15), 1,
      anon_sym_incremental_where,
    ACTIONS(17), 1,
      anon_sym_input,
    ACTIONS(19), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    ACTIONS(25), 1,
      sym_sql_text,
    STATE(3), 8,
      sym_config_block,
      sym_js_block,
      sym_pre_operations_block,
      sym_post_operations_block,
      sym_incremental_where_block,
      sym_input_block,
      sym_interpolation,
      aux_sym_source_file_repeat1,
  [41] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    ACTIONS(29), 1,
      anon_sym_config,
    ACTIONS(32), 1,
      anon_sym_js,
    ACTIONS(35), 1,
      anon_sym_pre_operations,
    ACTIONS(38), 1,
      anon_sym_post_operations,
    ACTIONS(41), 1,
      anon_sym_incremental_where,
    ACTIONS(44), 1,
      anon_sym_input,
    ACTIONS(47), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(50), 1,
      sym_sql_text,
    STATE(3), 8,
      sym_config_block,
      sym_js_block,
      sym_pre_operations_block,
      sym_post_operations_block,
      sym_incremental_where_block,
      sym_input_block,
      sym_interpolation,
      aux_sym_source_file_repeat1,
  [82] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 9,
      sym_sql_text,
      ts_builtin_sym_end,
      anon_sym_config,
      anon_sym_js,
      anon_sym_pre_operations,
      anon_sym_post_operations,
      anon_sym_incremental_where,
      anon_sym_input,
      anon_sym_DOLLAR_LBRACE,
  [97] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 9,
      sym_sql_text,
      ts_builtin_sym_end,
      anon_sym_config,
      anon_sym_js,
      anon_sym_pre_operations,
      anon_sym_post_operations,
      anon_sym_incremental_where,
      anon_sym_input,
      anon_sym_DOLLAR_LBRACE,
  [112] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 9,
      sym_sql_text,
      ts_builtin_sym_end,
      anon_sym_config,
      anon_sym_js,
      anon_sym_pre_operations,
      anon_sym_post_operations,
      anon_sym_incremental_where,
      anon_sym_input,
      anon_sym_DOLLAR_LBRACE,
  [127] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 9,
      sym_sql_text,
      ts_builtin_sym_end,
      anon_sym_config,
      anon_sym_js,
      anon_sym_pre_operations,
      anon_sym_post_operations,
      anon_sym_incremental_where,
      anon_sym_input,
      anon_sym_DOLLAR_LBRACE,
  [142] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(61), 9,
      sym_sql_text,
      ts_builtin_sym_end,
      anon_sym_config,
      anon_sym_js,
      anon_sym_pre_operations,
      anon_sym_post_operations,
      anon_sym_incremental_where,
      anon_sym_input,
      anon_sym_DOLLAR_LBRACE,
  [157] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(63), 9,
      sym_sql_text,
      ts_builtin_sym_end,
      anon_sym_config,
      anon_sym_js,
      anon_sym_pre_operations,
      anon_sym_post_operations,
      anon_sym_incremental_where,
      anon_sym_input,
      anon_sym_DOLLAR_LBRACE,
  [172] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 9,
      sym_sql_text,
      ts_builtin_sym_end,
      anon_sym_config,
      anon_sym_js,
      anon_sym_pre_operations,
      anon_sym_post_operations,
      anon_sym_incremental_where,
      anon_sym_input,
      anon_sym_DOLLAR_LBRACE,
  [187] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 9,
      sym_sql_text,
      ts_builtin_sym_end,
      anon_sym_config,
      anon_sym_js,
      anon_sym_pre_operations,
      anon_sym_post_operations,
      anon_sym_incremental_where,
      anon_sym_input,
      anon_sym_DOLLAR_LBRACE,
  [202] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 9,
      sym_sql_text,
      ts_builtin_sym_end,
      anon_sym_config,
      anon_sym_js,
      anon_sym_pre_operations,
      anon_sym_post_operations,
      anon_sym_incremental_where,
      anon_sym_input,
      anon_sym_DOLLAR_LBRACE,
  [217] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 9,
      sym_sql_text,
      ts_builtin_sym_end,
      anon_sym_config,
      anon_sym_js,
      anon_sym_pre_operations,
      anon_sym_post_operations,
      anon_sym_incremental_where,
      anon_sym_input,
      anon_sym_DOLLAR_LBRACE,
  [232] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 9,
      sym_sql_text,
      ts_builtin_sym_end,
      anon_sym_config,
      anon_sym_js,
      anon_sym_pre_operations,
      anon_sym_post_operations,
      anon_sym_incremental_where,
      anon_sym_input,
      anon_sym_DOLLAR_LBRACE,
  [247] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 9,
      sym_sql_text,
      ts_builtin_sym_end,
      anon_sym_config,
      anon_sym_js,
      anon_sym_pre_operations,
      anon_sym_post_operations,
      anon_sym_incremental_where,
      anon_sym_input,
      anon_sym_DOLLAR_LBRACE,
  [262] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 9,
      sym_sql_text,
      ts_builtin_sym_end,
      anon_sym_config,
      anon_sym_js,
      anon_sym_pre_operations,
      anon_sym_post_operations,
      anon_sym_incremental_where,
      anon_sym_input,
      anon_sym_DOLLAR_LBRACE,
  [277] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 9,
      sym_sql_text,
      ts_builtin_sym_end,
      anon_sym_config,
      anon_sym_js,
      anon_sym_pre_operations,
      anon_sym_post_operations,
      anon_sym_incremental_where,
      anon_sym_input,
      anon_sym_DOLLAR_LBRACE,
  [292] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(81), 9,
      sym_sql_text,
      ts_builtin_sym_end,
      anon_sym_config,
      anon_sym_js,
      anon_sym_pre_operations,
      anon_sym_post_operations,
      anon_sym_incremental_where,
      anon_sym_input,
      anon_sym_DOLLAR_LBRACE,
  [307] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 1,
      anon_sym_LBRACE,
    ACTIONS(85), 1,
      anon_sym_COMMA,
    ACTIONS(87), 1,
      anon_sym_LBRACK,
    ACTIONS(89), 1,
      anon_sym_RBRACK,
    ACTIONS(91), 1,
      sym_js_expression,
    STATE(39), 3,
      sym_object,
      sym_array,
      sym__value,
  [331] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      anon_sym_RBRACE,
    ACTIONS(95), 1,
      anon_sym_COMMA,
    ACTIONS(97), 1,
      sym_property_identifier,
    STATE(36), 1,
      sym_pair,
    STATE(67), 1,
      sym_string,
    ACTIONS(99), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
  [354] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 1,
      sym_property_identifier,
    ACTIONS(101), 1,
      anon_sym_RBRACE,
    ACTIONS(103), 1,
      anon_sym_COMMA,
    STATE(51), 1,
      sym_pair,
    STATE(67), 1,
      sym_string,
    ACTIONS(99), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
  [377] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 1,
      anon_sym_LBRACE,
    ACTIONS(87), 1,
      anon_sym_LBRACK,
    ACTIONS(105), 1,
      anon_sym_RBRACK,
    ACTIONS(107), 1,
      sym_js_expression,
    STATE(55), 3,
      sym_object,
      sym_array,
      sym__value,
  [398] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 1,
      anon_sym_LBRACE,
    ACTIONS(87), 1,
      anon_sym_LBRACK,
    ACTIONS(107), 1,
      sym_js_expression,
    ACTIONS(109), 1,
      anon_sym_RBRACK,
    STATE(55), 3,
      sym_object,
      sym_array,
      sym__value,
  [419] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 1,
      anon_sym_LBRACE,
    ACTIONS(87), 1,
      anon_sym_LBRACK,
    ACTIONS(111), 1,
      sym_js_expression,
    STATE(63), 3,
      sym_object,
      sym_array,
      sym__value,
  [437] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 1,
      sym_property_identifier,
    ACTIONS(113), 1,
      anon_sym_RBRACE,
    STATE(57), 1,
      sym_pair,
    STATE(67), 1,
      sym_string,
    ACTIONS(99), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
  [457] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 1,
      sym_property_identifier,
    ACTIONS(115), 1,
      anon_sym_RBRACE,
    STATE(57), 1,
      sym_pair,
    STATE(67), 1,
      sym_string,
    ACTIONS(99), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
  [477] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 1,
      anon_sym_LBRACE,
    ACTIONS(87), 1,
      anon_sym_LBRACK,
    ACTIONS(107), 1,
      sym_js_expression,
    STATE(55), 3,
      sym_object,
      sym_array,
      sym__value,
  [495] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 1,
      sym_property_identifier,
    ACTIONS(117), 1,
      anon_sym_RBRACE,
    STATE(57), 1,
      sym_pair,
    STATE(67), 1,
      sym_string,
    ACTIONS(99), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
  [515] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 1,
      sym_property_identifier,
    ACTIONS(119), 1,
      anon_sym_RBRACE,
    STATE(57), 1,
      sym_pair,
    STATE(67), 1,
      sym_string,
    ACTIONS(99), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
  [535] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 1,
      anon_sym_RBRACE,
    ACTIONS(123), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(125), 1,
      sym_block_sql_text,
    STATE(31), 2,
      sym_interpolation,
      aux_sym__sql_block_body_repeat1,
  [552] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 1,
      anon_sym_RBRACE,
    ACTIONS(129), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(132), 1,
      sym_block_sql_text,
    STATE(31), 2,
      sym_interpolation,
      aux_sym__sql_block_body_repeat1,
  [569] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 1,
      sym_property_identifier,
    STATE(57), 1,
      sym_pair,
    STATE(67), 1,
      sym_string,
    ACTIONS(99), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
  [586] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(135), 1,
      anon_sym_RBRACE,
    ACTIONS(137), 1,
      sym_block_sql_text,
    STATE(30), 2,
      sym_interpolation,
      aux_sym__sql_block_body_repeat1,
  [603] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 1,
      anon_sym_RBRACE,
    ACTIONS(139), 1,
      anon_sym_COMMA,
    STATE(37), 1,
      aux_sym_object_repeat1,
  [616] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 1,
      anon_sym_RBRACE,
    ACTIONS(141), 1,
      anon_sym_COMMA,
    STATE(37), 1,
      aux_sym_object_repeat1,
  [629] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 1,
      anon_sym_RBRACE,
    ACTIONS(145), 1,
      anon_sym_COMMA,
    STATE(34), 1,
      aux_sym_object_repeat1,
  [642] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 1,
      anon_sym_RBRACE,
    ACTIONS(149), 1,
      anon_sym_COMMA,
    STATE(37), 1,
      aux_sym_object_repeat1,
  [655] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 3,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [664] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(154), 1,
      anon_sym_COMMA,
    ACTIONS(156), 1,
      anon_sym_RBRACK,
    STATE(40), 1,
      aux_sym_array_repeat1,
  [677] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 1,
      anon_sym_RBRACK,
    ACTIONS(158), 1,
      anon_sym_COMMA,
    STATE(42), 1,
      aux_sym_array_repeat1,
  [690] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(160), 3,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [699] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(162), 1,
      anon_sym_COMMA,
    ACTIONS(165), 1,
      anon_sym_RBRACK,
    STATE(42), 1,
      aux_sym_array_repeat1,
  [712] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 3,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [721] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(61), 3,
      sym_block_sql_text,
      anon_sym_RBRACE,
      anon_sym_DOLLAR_LBRACE,
  [730] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 3,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [739] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 3,
      sym_block_sql_text,
      anon_sym_RBRACE,
      anon_sym_DOLLAR_LBRACE,
  [748] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 3,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [757] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 3,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [766] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(81), 3,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [775] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(62), 1,
      sym_string,
    ACTIONS(99), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
  [786] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 1,
      anon_sym_RBRACE,
    ACTIONS(171), 1,
      anon_sym_COMMA,
    STATE(35), 1,
      aux_sym_object_repeat1,
  [799] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 3,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [808] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(175), 1,
      anon_sym_LBRACE,
    STATE(6), 1,
      sym__sql_block_body,
  [818] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 1,
      anon_sym_LBRACE,
    STATE(9), 1,
      sym_object,
  [828] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [836] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(175), 1,
      anon_sym_LBRACE,
    STATE(7), 1,
      sym__sql_block_body,
  [846] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [854] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(179), 1,
      anon_sym_RBRACE,
    ACTIONS(181), 1,
      sym_js_body,
  [864] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(183), 1,
      anon_sym_RBRACE,
    ACTIONS(185), 1,
      sym_js_body,
  [874] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(175), 1,
      anon_sym_LBRACE,
    STATE(5), 1,
      sym__sql_block_body,
  [884] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 1,
      anon_sym_RBRACE,
    ACTIONS(189), 1,
      sym_js_body,
  [894] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(175), 1,
      anon_sym_LBRACE,
    STATE(14), 1,
      sym__sql_block_body,
  [904] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(191), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [912] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(193), 2,
      anon_sym_LBRACE,
      anon_sym_COLON,
  [920] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 1,
      anon_sym_RBRACE,
  [927] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 1,
      ts_builtin_sym_end,
  [934] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(199), 1,
      anon_sym_COLON,
  [941] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(156), 1,
      anon_sym_RBRACK,
  [948] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 1,
      anon_sym_LBRACE,
  [955] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(203), 1,
      anon_sym_RBRACE,
  [962] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 1,
      anon_sym_RBRACE,
  [969] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(205), 1,
      anon_sym_RBRACE,
  [976] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 1,
      anon_sym_RBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 41,
  [SMALL_STATE(4)] = 82,
  [SMALL_STATE(5)] = 97,
  [SMALL_STATE(6)] = 112,
  [SMALL_STATE(7)] = 127,
  [SMALL_STATE(8)] = 142,
  [SMALL_STATE(9)] = 157,
  [SMALL_STATE(10)] = 172,
  [SMALL_STATE(11)] = 187,
  [SMALL_STATE(12)] = 202,
  [SMALL_STATE(13)] = 217,
  [SMALL_STATE(14)] = 232,
  [SMALL_STATE(15)] = 247,
  [SMALL_STATE(16)] = 262,
  [SMALL_STATE(17)] = 277,
  [SMALL_STATE(18)] = 292,
  [SMALL_STATE(19)] = 307,
  [SMALL_STATE(20)] = 331,
  [SMALL_STATE(21)] = 354,
  [SMALL_STATE(22)] = 377,
  [SMALL_STATE(23)] = 398,
  [SMALL_STATE(24)] = 419,
  [SMALL_STATE(25)] = 437,
  [SMALL_STATE(26)] = 457,
  [SMALL_STATE(27)] = 477,
  [SMALL_STATE(28)] = 495,
  [SMALL_STATE(29)] = 515,
  [SMALL_STATE(30)] = 535,
  [SMALL_STATE(31)] = 552,
  [SMALL_STATE(32)] = 569,
  [SMALL_STATE(33)] = 586,
  [SMALL_STATE(34)] = 603,
  [SMALL_STATE(35)] = 616,
  [SMALL_STATE(36)] = 629,
  [SMALL_STATE(37)] = 642,
  [SMALL_STATE(38)] = 655,
  [SMALL_STATE(39)] = 664,
  [SMALL_STATE(40)] = 677,
  [SMALL_STATE(41)] = 690,
  [SMALL_STATE(42)] = 699,
  [SMALL_STATE(43)] = 712,
  [SMALL_STATE(44)] = 721,
  [SMALL_STATE(45)] = 730,
  [SMALL_STATE(46)] = 739,
  [SMALL_STATE(47)] = 748,
  [SMALL_STATE(48)] = 757,
  [SMALL_STATE(49)] = 766,
  [SMALL_STATE(50)] = 775,
  [SMALL_STATE(51)] = 786,
  [SMALL_STATE(52)] = 799,
  [SMALL_STATE(53)] = 808,
  [SMALL_STATE(54)] = 818,
  [SMALL_STATE(55)] = 828,
  [SMALL_STATE(56)] = 836,
  [SMALL_STATE(57)] = 846,
  [SMALL_STATE(58)] = 854,
  [SMALL_STATE(59)] = 864,
  [SMALL_STATE(60)] = 874,
  [SMALL_STATE(61)] = 884,
  [SMALL_STATE(62)] = 894,
  [SMALL_STATE(63)] = 904,
  [SMALL_STATE(64)] = 912,
  [SMALL_STATE(65)] = 920,
  [SMALL_STATE(66)] = 927,
  [SMALL_STATE(67)] = 934,
  [SMALL_STATE(68)] = 941,
  [SMALL_STATE(69)] = 948,
  [SMALL_STATE(70)] = 955,
  [SMALL_STATE(71)] = 962,
  [SMALL_STATE(72)] = 969,
  [SMALL_STATE(73)] = 976,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(69),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 3, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pre_operations_block, 2, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_post_operations_block, 2, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_incremental_where_block, 2, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interpolation, 2, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_config_block, 2, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 2, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_js_block, 3, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__sql_block_body, 2, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interpolation, 3, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_input_block, 3, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 4, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_js_block, 4, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__sql_block_body, 3, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 5, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__sql_block_body_repeat1, 2, 0, 0),
  [129] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__sql_block_body_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [132] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__sql_block_body_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_object_repeat1, 2, 0, 0),
  [149] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_object_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 4, 0, 0),
  [162] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 5, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pair, 3, 0, 1),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1, 0, 0),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [197] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_sql_text = 0,
  ts_external_token_block_sql_text = 1,
  ts_external_token_js_body = 2,
  ts_external_token_js_expression = 3,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_sql_text] = sym_sql_text,
  [ts_external_token_block_sql_text] = sym_block_sql_text,
  [ts_external_token_js_body] = sym_js_body,
  [ts_external_token_js_expression] = sym_js_expression,
};

static const bool ts_external_scanner_states[6][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_sql_text] = true,
    [ts_external_token_block_sql_text] = true,
    [ts_external_token_js_body] = true,
    [ts_external_token_js_expression] = true,
  },
  [2] = {
    [ts_external_token_sql_text] = true,
  },
  [3] = {
    [ts_external_token_js_expression] = true,
  },
  [4] = {
    [ts_external_token_block_sql_text] = true,
  },
  [5] = {
    [ts_external_token_js_body] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_sqlx_external_scanner_create(void);
void tree_sitter_sqlx_external_scanner_destroy(void *);
bool tree_sitter_sqlx_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_sqlx_external_scanner_serialize(void *, char *);
void tree_sitter_sqlx_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_sqlx(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_sqlx_external_scanner_create,
      tree_sitter_sqlx_external_scanner_destroy,
      tree_sitter_sqlx_external_scanner_scan,
      tree_sitter_sqlx_external_scanner_serialize,
      tree_sitter_sqlx_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
